### ISSUE TITLE
1.8.8 support

### ISSUE THREAD

**Issue by mantrakp04** [riku6460/SpigotProxy#11]
is there any way to run this on 1.8.8?

**Comment by riku6460** [comment]
Not supported. Works with 1.12.2 or later.

**Comment by mantrakp04** [comment]
is there any alternative for 1.8.8 servers for them to be able to join with proxy protocol?

**Comment by riku6460** [comment]
Velocity and BungeeCord supports Proxy Protocol.

https://docs.papermc.io/velocity/configuration#advanced-section

https://www.spigotmc.org/wiki/bungeecord-configuration-guide/
