### ISSUE TITLE
Release 1.0.1 JAR 

### ISSUE THREAD

**Issue by timvisee** [riku6460/SpigotProxy#5]
Would you mind to release the latest 1.0.1 JAR through GitHub releases?

JAR for users landing here in the mean time: https://send.vis.ee/download/ea787e1c8d4eca61/#-JsEtuz8_7wag6E_J9vuQg

Related: https://github.com/riku6460/SpigotProxy/issues/2

**Comment by riku6460** [comment]
Released

https://github.com/riku6460/SpigotProxy/releases/tag/v1.0.1

**Comment by timvisee** [comment]
Fantastic. Thanks for your quick action!
