### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by megatron0001** [riku6460/SpigotProxy#6]
Hi,

Just wondering if you could add an IP whitelisting feature in the config like
"https://cdn.server.com/ips" and it would download/curl all the ips from the url and only allow those connections
into the server via haproxy like tcpshield's system.

**Comment by riku6460** [comment]
You can create a firewall using iptables or something like that.

**Comment by megatron0001** [comment]
> You can create a firewall using iptables or something like that.

yes but what about windows or a server hosting?
